  title: Statistical issues in healthcare provider comparisons
  description: An online seminar series and mailing list for researchers and practitioners working on methodological aspects of provider comparisons
